services:
  - type: web
    name: random-forest-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    autoDeploy: true
    pythonVersion: 3.10
