# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmnJ7mHBh7OUrdsUoCAa7GyuX1vNpwW6
"""

from flask import Flask, render_template, request
import joblib
import pandas as pd

app = Flask(__name__)
model = joblib.load("model.pkl")  # Asegurate de tenerlo en la carpeta raíz

@app.route("/", methods=["GET", "POST"])
def home():
    prediction = None

    if request.method == "POST":
        try:
            # Tomar valores del formulario
            rooms = int(request.form["rooms"])
            bathrooms = int(request.form["bathrooms"])
            surface_total = float(request.form["surface_total"])
            surface_covered = float(request.form["surface_covered"])
            lat = float(request.form["lat"])
            lon = float(request.form["lon"])
            prop_type = request.form["prop_type"]
            grupo_precio = request.form["grupo_precio"]

            # Crear DataFrame igual al entrenamiento
            nuevos_casos = pd.DataFrame({
                "rooms": [rooms],
                "bathrooms": [bathrooms],
                "surface_total": [surface_total],
                "surface_covered": [surface_covered],
                "lat": [lat],
                "lon": [lon],
                "prop_type": [prop_type],
                "Grupo_Precio": [grupo_precio],
            })

            # Features derivadas
            nuevos_casos["ratio_covered_total"] = surface_covered / (surface_total + 1e-5)
            nuevos_casos["total_rooms_surface_ratio"] = surface_total / (rooms + 1)
            nuevos_casos["covered_rooms_surface_ratio"] = surface_covered / (rooms + 1)

            # Predecir
            pred = model.predict(nuevos_casos)[0]
            prediction = f"${pred:,.2f}"

        except Exception as e:
            prediction = f"Error: {str(e)}"

    return render_template("index.html", prediction=prediction)